# Generated by Django 3.1.6 on 2021-02-11 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relatedfielddemo', '0002_auto_20210211_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='relatedfielddemo.questionset'),
        ),
    ]
